import { CafeMatch } from '@/types';

export const sampleCafeMatches: CafeMatch[] = [
  {
    place: {
      id: 'analog-coffee',
      displayName: 'Analog Coffee Roasters',
      formattedAddress: '123 Sample St, Portland, OR',
      rating: 4.7,
      userRatingCount: 214,
      priceLevel: 2,
      primaryType: 'cafe',
      types: ['cafe', 'coffee_shop', 'bakery'],
      photos: [],
      photoUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
      regularOpeningHours: undefined,
      outdoorSeating: true,
      servesCoffee: true,
      servesBreakfast: true,
      allowsDogs: true,
      goodForGroups: false,
    },
    score: 92.3,
    reasoning: 'Sun-soaked roastery with rotating single origins and an analog hi-fi bar that mirrors your SF reference spot.',
    matchedKeywords: ['Roastery', 'Laptop friendly', 'Outdoor seating'],
    distanceToCenter: 1.2,
    typeOverlapDetails: 'Shares specialty cafe characteristics with Analog SF.',
  },
  {
    place: {
      id: 'midnight-espresso',
      displayName: 'Midnight Espresso Lab',
      formattedAddress: '456 Brooklyn Ave, New York, NY',
      rating: 4.5,
      userRatingCount: 389,
      priceLevel: 3,
      primaryType: 'cafe',
      types: ['cafe', 'coffee_shop'],
      photos: [],
      photoUrl: 'https://images.unsplash.com/photo-1459257868276-5e65389e2722?auto=format&fit=crop&w=900&q=80',
      servesDinner: false,
      servesBrunch: true,
      takeout: true,
      reservable: false,
      liveMusic: true,
    },
    score: 88.6,
    reasoning: 'Late-night espresso lab with playful signature drinks and live vinyl sets—great for your night owl vibe.',
    matchedKeywords: ['Night owl', 'Signature drinks', 'Live vinyl sets'],
    distanceToCenter: 3.4,
    typeOverlapDetails: 'Shares specialty coffee focus and late hours.',
  },
  {
    place: {
      id: 'gallery-brew',
      displayName: 'Gallery Brew House',
      formattedAddress: '789 Mission St, San Francisco, CA',
      rating: 4.8,
      userRatingCount: 512,
      priceLevel: 2,
      primaryType: 'cafe',
      types: ['cafe', 'art_gallery'],
      photos: [],
      photoUrl: 'https://images.unsplash.com/photo-1464306076886-da185f6a9d12?auto=format&fit=crop&w=900&q=80',
      servesLunch: true,
      servesVegetarianFood: true,
      goodForGroups: true,
    },
    score: 95.1,
    reasoning: 'Art-forward brew house that mixes pour-over flights with rotating local gallery walls—perfect if you loved Modern Times.',
    matchedKeywords: ['Art gallery', 'Pour-over flights', 'Local artists'],
    distanceToCenter: 0.8,
    typeOverlapDetails: 'Shares modern art-forward ambience with your origin cafes.',
  },
];

